CREATE DATABASE LCS CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE TABLE LIBRARY
(
    ID           BIGINT PRIMARY KEY COMMENT 'ID',
    NAME         VARCHAR(64) NOT NULL COMMENT 'LIBRARY NAME',
    CREATED_BY   VARCHAR(64) COMMENT 'CREATED BY',
    CREATED_TIME TIMESTAMP COMMENT 'CREATED TIME'
)
    COMMENT 'LIBRARY TABLE';
CREATE TABLE USER
(
    ID           BIGINT PRIMARY KEY COMMENT 'ID',
    USER_NAME    VARCHAR(64) NOT NULL COMMENT 'USER NAME',
    CREATED_BY   VARCHAR(64) COMMENT 'CREATED BY',
    CREATED_TIME TIMESTAMP COMMENT 'CREATED TIME'
)
    COMMENT 'USER TABLE';
CREATE TABLE BOOK
(
    ID              BIGINT PRIMARY KEY COMMENT 'ID',
    CATEGORY_ID     BIGINT COMMENT 'CATEGORY_ID',
    LIBRARY_ID      BIGINT COMMENT 'LIBRARY_ID',
    REAL_LIBRARY_ID BIGINT COMMENT 'REAL_LIBRARY_ID',
    SHELF_ID        BIGINT COMMENT 'SHELF_ID',
    TITLE           VARCHAR(256) COMMENT 'TITLE',
    SUMMARY         VARCHAR(512) COMMENT 'SUMMARY',
    IMAGE           VARCHAR(256) COMMENT 'IMAGE',
    AUTHOR          VARCHAR(256) COMMENT 'AUTHOR',
    SUBJECT         VARCHAR(64) COMMENT 'SUBJECT',
    FORMAT          VARCHAR(64) COMMENT 'FORMAT',
    PUBLISHER       VARCHAR(256) COMMENT 'PUBLISHER',
    PUBLISHED_DATE  TIMESTAMP COMMENT 'PUBLISHED DATE',
    LANGUAGE        VARCHAR(64) COMMENT 'LANGUAGE',
    COUNTRY         VARCHAR(64) COMMENT 'COUNTRY',
    ISBN            VARCHAR(64) COMMENT 'ISBN',
    STATUS          VARCHAR(16) COMMENT 'STATUS',
    CREATED_BY      VARCHAR(64) COMMENT 'CREATED BY',
    CREATED_TIME    TIMESTAMP COMMENT 'CREATED TIME'
) COMMENT 'BOOK TABLE';
CREATE TABLE BOOK_REQUEST
(
    ID             BIGINT PRIMARY KEY COMMENT 'ID',
    LIBRARY_ID     BIGINT COMMENT 'LIBRARY_ID',
    TITLE          VARCHAR(256) COMMENT 'TITLE',
    REASON         VARCHAR(256) COMMENT 'REASON',
    IMAGE          VARCHAR(256) COMMENT 'IMAGE',
    AUTHOR         VARCHAR(256) COMMENT 'AUTHOR',
    SUBJECT        VARCHAR(64) COMMENT 'SUBJECT',
    FORMAT         VARCHAR(64) COMMENT 'FORMAT',
    PUBLISHER      VARCHAR(256) COMMENT 'PUBLISHER',
    PUBLISHED_DATE TIMESTAMP COMMENT 'PUBLISHED DATE',
    LANGUAGE       VARCHAR(64) COMMENT 'LANGUAGE',
    COUNTRY        VARCHAR(64) COMMENT 'COUNTRY',
    ISBN           VARCHAR(64) COMMENT 'ISBN',
    STATUS         VARCHAR(16) COMMENT 'STATUS',
    VALIDATED_BY   VARCHAR(64) COMMENT 'VALIDATED BY',
    VALIDATED_TIME TIMESTAMP COMMENT 'VALIDATED TIME',
    CREATED_BY     VARCHAR(64) COMMENT 'CREATED BY',
    CREATED_TIME   TIMESTAMP COMMENT 'CREATED TIME'
) COMMENT 'BOOK REQUEST TABLE';
CREATE TABLE IF NOT EXISTS RESERVATION
(
    ID                   BIGINT PRIMARY KEY COMMENT 'ID',
    SOURCE_ID            BIGINT UNIQUE KEY COMMENT 'ID',
    REAL_LIBRARY_ID      BIGINT COMMENT 'REAL LIBRARY ID',
    REAL_SPOT_ID         BIGINT COMMENT 'REAL SPOT ID',
    REAL_SHELF_ID        BIGINT COMMENT 'REAL SHELF ID',
    TARGET_LIBRARY_ID    BIGINT COMMENT 'TARGET LIBRARY ID',
    TARGET_SPOT_ID       BIGINT COMMENT 'TARGET SPOT ID',
    TARGET_SHELF_ID      BIGINT COMMENT 'TARGET SHELF ID',
    USER_ID              BIGINT COMMENT 'USER ID',
    EXPECTED_PICKUP_TIME TIMESTAMP COMMENT 'EXPECTED PICKUP TIME',
    REAL_PICKUP_TIME     TIMESTAMP COMMENT 'REAL PICKUP TIME',
    BOOK_ID              BIGINT COMMENT 'BOOK ID',
    BOOK_LIBRARY_ID      BIGINT COMMENT 'BOOK LIBRARY ID',
    BOOK_TITLE           VARCHAR(256) COMMENT 'BOOK TITLE',
    BOOK_IMAGE           VARCHAR(256) COMMENT 'BOOK IMAGE',
    BOOK_AUTHOR          VARCHAR(256) COMMENT 'BOOK AUTHOR',
    BOOK_FORMAT          VARCHAR(64) COMMENT 'BOOK FORMAT',
    BOOK_ISBN            VARCHAR(64) COMMENT 'BOOK ISBN',
    STATUS               VARCHAR(16) COMMENT 'STATUS',
    CREATED_BY           VARCHAR(64) COMMENT 'CREATED BY',
    CREATED_TIME         TIMESTAMP COMMENT 'CREATED TIME'
) COMMENT 'BOOK RESERVATION TABLE';
